name: Create model on commit
on:
  push:
    branches: [main]

jobs:
  run-model:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
        
      - name: Install Dependacies
        run: |
          python -m pip install --upgrate pip
          python pip install -r requirements.txt
        
      - name: Run Model
        run:
          python main.py

      - name: Artifact making
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model/model.pkl