name: Create model on commit
on:
  push:
    branches: [main]

jobs:
  run_model:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout main
         uses: actions/checkout@v3

       - name: Install Python
         uses: action/setup-python@v4
         with:
           python-version: '3.13'
      
       - name: Install dependacies
         run: | 
           python pip -m install --upgrade pip
           pip install -r requirement.txt

       - name: Run model
         run: |
           python main.py

       - name: Update artifacts
         uses: actions/upload-artifact@v4
           with:
             name: Model
             path: model/model.pkl