name: Bump version

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Bump Version
        id: bump
        run: |
          if [ ! -f version.txt ]; then
            echo "1" > version.txt
          fi
          version=$(cat version.txt)
          new_version=$((version + 1))
          echo $new_version > version.txt
          git config user.name "github bot"
          git config user.email "github-actions@users.noreply.github.com"
          git add version.txt
          git commit -m "chore: bump version to v$new_version"
          git tag v$new_version
          git push origin main --follow-tags
          echo "new_version=v$new_version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_version }}
          release_name: "Release ${{ steps.bump.outputs.new_version }}"
          body: "Automated release of version ${{ steps.bump.outputs.new_version }}"
          draft: false
          prerelease: false

      - name: Upload version file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: version.txt
          asset_name: version.txt
          asset_content_type: text/plain